### Ejercicio 1

In [1]:
import numpy as np
array = np.arange(0,100,4)
print(array)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


### Ejercicio 2

In [4]:
import numpy as np
array = np.arange(20).reshape(5,4)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


### Ejercicio 3

In [5]:
import numpy as np
array = np.arange(20)
array = np.flip(array)
print(array)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


### Ejercicio 4

In [35]:
import numpy as np
def invertir_filas(array):
    return np.flip(array,axis=0)
array = np.arange(20).reshape(5,4)
invertir_filas(array)

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

### Ejercicio 5

In [6]:
import numpy as np
array = np.arange(12).reshape(4, 3)
medias = np.mean(array, axis=0)
print(medias)

[4.5 5.5 6.5]


### Ejercicio 6

In [7]:
import numpy as np
array = np.arange(12)
def redimensionar(array):
    return array.reshape(4,3)
print(redimensionar(array))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### Ejercicio 7

In [29]:
import numpy as np
def redimensionar(array):
    longitud = len(array)
    if(np.sqrt(longitud) **2 == longitud):
        seccion = int(np.sqrt(longitud))
        print(array.reshape(seccion,seccion))
    else:
        print("No se puede redimensionar")
array = np.arange(25)
redimensionar(array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Ejercicio 8

In [41]:
import numpy as np
def maximo_de_fila(array):
    return np.max(array,axis=1)
array = np.arange(20).reshape(4,5)
maximo_de_fila(array)

array([ 4,  9, 14, 19])

### Ejercicio 9

In [69]:
import numpy as np
def contar_valores(array):
    valores, cuenta = np.unique(array, return_counts=True)
    cuenta = zip(valores,cuenta)
    return [a for a in cuenta]
array = np.array([1,1,1,2,2,3,3,3,3])
contar_valores(array)

[(1, 3), (2, 2), (3, 4)]

### Ejercicio 10

In [74]:
import numpy as np
def normalizar_array(array):
    media = np.mean(array)
    desviacion = np.std(array)
    return array-media/desviacion
array = np.arange(12).reshape(4,3)
normalizar_array(array)

array([[-1.59325501, -0.59325501,  0.40674499],
       [ 1.40674499,  2.40674499,  3.40674499],
       [ 4.40674499,  5.40674499,  6.40674499],
       [ 7.40674499,  8.40674499,  9.40674499]])