In [22]:
# https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/
# univariate lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Input
import numpy as np

In [3]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [4]:
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
#X, y = split_sequence(raw_seq, n_steps)

windows = np.lib.stride_tricks.sliding_window_view(raw_seq, window_shape=n_steps)
X = array(windows[:-1])  # Todas las ventanas menos la última. Hay que convertir a array numpy
y = array(raw_seq[n_steps:])  # Lo que predices (el siguiente valor después de cada ventana)

print(X)
print(y)

[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]]
[40 50 60 70 80 90]


In [20]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

# define model
model = Sequential()
model.add(Input(shape=(n_steps, n_features)))
model.add(LSTM(50, activation='relu', return_sequences=True))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# fit model
model.fit(X, y, epochs=400)

Epoch 1/400
1/1 [==============================] - 1s 1s/step - loss: 4387.0542
Epoch 2/400
1/1 [==============================] - 0s 7ms/step - loss: 4290.1245
Epoch 3/400
1/1 [==============================] - 0s 7ms/step - loss: 4188.1460
Epoch 4/400
1/1 [==============================] - 0s 7ms/step - loss: 4078.9128
Epoch 5/400
1/1 [==============================] - 0s 7ms/step - loss: 3961.8428
Epoch 6/400
1/1 [==============================] - 0s 8ms/step - loss: 3840.0586
Epoch 7/400
1/1 [==============================] - 0s 6ms/step - loss: 3715.2961
Epoch 8/400
1/1 [==============================] - 0s 7ms/step - loss: 3586.2800
Epoch 9/400
1/1 [==============================] - 0s 5ms/step - loss: 3448.0830
Epoch 10/400
1/1 [==============================] - 0s 8ms/step - loss: 3305.5398
Epoch 11/400
1/1 [==============================] - 0s 5ms/step - loss: 3160.2529
Epoch 12/400
1/1 [==============================] - 0s 8ms/step - loss: 3010.0593
Epoch 13/400
1/1 [========

In [21]:
# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[100.69539]]
